# based on an example from https://github.com/r-lib/actions/tree/master/examples

name: Update data PHZH ILIAS

on:
  push:
    paths:
    - 'data_ilias/**'

jobs:
  update_data:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup R and its depedencies
    - uses: r-lib/actions/setup-r@master
    - name: Install R dependencies
      run: |
        install.packages("tidyverse")
        install.packages("openxlsx")
      shell: Rscript {0}
      
    # Prepare data
    - name: Prepare data with prepareILIASdata.R
      run: Rscript prepareILIASdata.R

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update Bildung_IliasNutzung.csv
        branch: ${{ github.head_ref }}
